// <auto-generated />
using System;
using GraniteServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GraniteServer.Data.Migrations.Sqlite
{
    [DbContext(typeof(GraniteDataContextSqlite))]
    partial class GraniteDataContextSqliteModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.13");

            modelBuilder.Entity("GraniteServer.Data.Entities.ModEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("Comments")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Created")
                        .HasColumnType("TEXT");

                    b.Property<int>("Downloads")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Follows")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HomePageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("IssueTrackerUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastChecked")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastReleased")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoFile")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoFileDb")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoFilename")
                        .HasColumnType("TEXT");

                    b.Property<long>("ModId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModIdStr")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Side")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceCodeUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrailerVideoUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("TrendingPoints")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("UrlAlias")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("WikiUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModId")
                        .IsUnique();

                    b.HasIndex("ModIdStr")
                        .IsUnique();

                    b.ToTable("Mods");
                });

            modelBuilder.Entity("GraniteServer.Data.Entities.ModReleaseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Changelog")
                        .HasColumnType("TEXT");

                    b.Property<string>("Created")
                        .HasColumnType("TEXT");

                    b.Property<int>("Downloads")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("FileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Filename")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("MainFile")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ModId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModIdStr")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModVersion")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long>("ReleaseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModId");

                    b.HasIndex("ReleaseId")
                        .IsUnique();

                    b.ToTable("ModReleases");
                });

            modelBuilder.Entity("GraniteServer.Data.Entities.ModServerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("InstalledReleaseId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ModId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RunningReleaseId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InstalledReleaseId");

                    b.HasIndex("ModId");

                    b.HasIndex("RunningReleaseId");

                    b.HasIndex("ServerId", "ModId")
                        .IsUnique();

                    b.ToTable("ModServers");
                });

            modelBuilder.Entity("GraniteServer.Data.Entities.PlayerEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstJoinDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastJoinDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id", "ServerId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("GraniteServer.Data.Entities.PlayerSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Duration")
                        .HasColumnType("REAL");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LeaveDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PlayerSessions");
                });

            modelBuilder.Entity("GraniteServer.Data.Entities.ServerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Servers");
                });

            modelBuilder.Entity("GraniteServer.Data.Entities.ModReleaseEntity", b =>
                {
                    b.HasOne("GraniteServer.Data.Entities.ModEntity", "Mod")
                        .WithMany("Releases")
                        .HasForeignKey("ModId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mod");
                });

            modelBuilder.Entity("GraniteServer.Data.Entities.ModServerEntity", b =>
                {
                    b.HasOne("GraniteServer.Data.Entities.ModReleaseEntity", "InstalledRelease")
                        .WithMany()
                        .HasForeignKey("InstalledReleaseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GraniteServer.Data.Entities.ModEntity", "Mod")
                        .WithMany()
                        .HasForeignKey("ModId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GraniteServer.Data.Entities.ModReleaseEntity", "RunningRelease")
                        .WithMany()
                        .HasForeignKey("RunningReleaseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GraniteServer.Data.Entities.ServerEntity", "Server")
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InstalledRelease");

                    b.Navigation("Mod");

                    b.Navigation("RunningRelease");

                    b.Navigation("Server");
                });

            modelBuilder.Entity("GraniteServer.Data.Entities.ModEntity", b =>
                {
                    b.Navigation("Releases");
                });
#pragma warning restore 612, 618
        }
    }
}
